"""initial migrations

Revision ID: aba91a6b9156
Revises: 
Create Date: 2022-11-01 12:28:16.453852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aba91a6b9156'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('Sno', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('img_file', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('Sno'),
    sa.UniqueConstraint('img_file'),
    sa.UniqueConstraint('slug')
    )
    op.drop_table('project_post')
    op.drop_constraint('contact_email_key', 'contact', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contact_email_key', 'contact', ['email'])
    op.create_table('project_post',
    sa.Column('Sno', sa.INTEGER(), server_default=sa.text('nextval(\'"project_post_Sno_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('img_file', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Sno', name='project_post_pkey'),
    sa.UniqueConstraint('img_file', name='project_post_img_file_key'),
    sa.UniqueConstraint('slug', name='project_post_slug_key')
    )
    op.drop_table('projects')
    # ### end Alembic commands ###
