"""add link

Revision ID: dac163997760
Revises: f4f00fb20763
Create Date: 2022-11-02 10:50:56.330492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dac163997760'
down_revision = 'f4f00fb20763'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_post', sa.Column('project_link', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_post', 'project_link')
    # ### end Alembic commands ###
