"""file link

Revision ID: f4f00fb20763
Revises: aba91a6b9156
Create Date: 2022-11-01 18:27:54.679998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4f00fb20763'
down_revision = 'aba91a6b9156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_constraint('project_post_img_file_key', 'project_post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_post_img_file_key', 'project_post', ['img_file'])
    op.create_table('projects',
    sa.Column('Sno', sa.INTEGER(), server_default=sa.text('nextval(\'"projects_Sno_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('img_file', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Sno', name='projects_pkey'),
    sa.UniqueConstraint('img_file', name='projects_img_file_key'),
    sa.UniqueConstraint('slug', name='projects_slug_key')
    )
    # ### end Alembic commands ###
